sh: sysctl: command not found
/anaconda/envs/g_dash/lib/python3.4/site-packages/numexpr/cpuinfo.py:76: UserWarning: [Errno 2] No such file or directory: 'sysctl'
  stacklevel=stacklevel + 1):
DEBUG: Checking if Agg_taxi_locations() is complete
/anaconda/envs/g_dash/lib/python3.4/site-packages/luigi/worker.py:295: UserWarning: Task Agg_taxi_locations() without outputs has no custom complete() method
  is_complete = task.complete()
INFO: Informed scheduler that task   Agg_taxi_locations__99914b932b   has status   PENDING
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 1
INFO: [pid 15391] Worker Worker(salt=911614392, workers=1, host=yennanliude-MBP, username=yennanliu, pid=15391) running   Agg_taxi_locations()
INFO: [pid 15391] Worker Worker(salt=911614392, workers=1, host=yennanliude-MBP, username=yennanliu, pid=15391) done      Agg_taxi_locations()
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   Agg_taxi_locations__99914b932b   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
INFO: Worker Worker(salt=911614392, workers=1, host=yennanliude-MBP, username=yennanliu, pid=15391) was stopped. Shutting down Keep-Alive thread
INFO: 
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 ran successfully:
    - 1 Agg_taxi_locations()

This progress looks :) because there were no failed tasks or missing external dependencies

===== Luigi Execution Summary =====

         lon      lat            timestamp
0  103.62328  1.29975  2017-11-12 16:41:05
1  103.62328  1.29975  2017-11-12 16:41:05
2  103.62328  1.29975  2017-11-12 16:41:05
3  103.62411  1.28180  2017-11-12 16:41:05
4  103.62411  1.28180  2017-11-12 16:41:05
Succefully save taxi location data as sqlite db to /output at 2017-11-12
sh: sysctl: command not found
/anaconda/envs/g_dash/lib/python3.4/site-packages/numexpr/cpuinfo.py:76: UserWarning: [Errno 2] No such file or directory: 'sysctl'
  stacklevel=stacklevel + 1):
DEBUG: Checking if Agg_taxi_locations() is complete
/anaconda/envs/g_dash/lib/python3.4/site-packages/luigi/worker.py:295: UserWarning: Task Agg_taxi_locations() without outputs has no custom complete() method
  is_complete = task.complete()
INFO: Informed scheduler that task   Agg_taxi_locations__99914b932b   has status   PENDING
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 1
INFO: [pid 15428] Worker Worker(salt=888873653, workers=1, host=yennanliude-MBP, username=yennanliu, pid=15428) running   Agg_taxi_locations()
INFO: [pid 15428] Worker Worker(salt=888873653, workers=1, host=yennanliude-MBP, username=yennanliu, pid=15428) done      Agg_taxi_locations()
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   Agg_taxi_locations__99914b932b   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
INFO: Worker Worker(salt=888873653, workers=1, host=yennanliude-MBP, username=yennanliu, pid=15428) was stopped. Shutting down Keep-Alive thread
INFO: 
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 ran successfully:
    - 1 Agg_taxi_locations()

This progress looks :) because there were no failed tasks or missing external dependencies

===== Luigi Execution Summary =====

       lon      lat            timestamp
0  103.628  1.31261  2017-11-12 16:42:06
1  103.628  1.31261  2017-11-12 16:42:06
2  103.628  1.31261  2017-11-12 16:42:06
3  103.628  1.31261  2017-11-12 16:42:06
4  103.628  1.31261  2017-11-12 16:42:06
Succefully save taxi location data as sqlite db to /output at 2017-11-12
sh: sysctl: command not found
/anaconda/envs/g_dash/lib/python3.4/site-packages/numexpr/cpuinfo.py:76: UserWarning: [Errno 2] No such file or directory: 'sysctl'
  stacklevel=stacklevel + 1):
DEBUG: Checking if Agg_taxi_locations() is complete
/anaconda/envs/g_dash/lib/python3.4/site-packages/luigi/worker.py:295: UserWarning: Task Agg_taxi_locations() without outputs has no custom complete() method
  is_complete = task.complete()
INFO: Informed scheduler that task   Agg_taxi_locations__99914b932b   has status   PENDING
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 1
INFO: [pid 15452] Worker Worker(salt=593850505, workers=1, host=yennanliude-MBP, username=yennanliu, pid=15452) running   Agg_taxi_locations()
INFO: [pid 15452] Worker Worker(salt=593850505, workers=1, host=yennanliude-MBP, username=yennanliu, pid=15452) done      Agg_taxi_locations()
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   Agg_taxi_locations__99914b932b   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
INFO: Worker Worker(salt=593850505, workers=1, host=yennanliude-MBP, username=yennanliu, pid=15452) was stopped. Shutting down Keep-Alive thread
INFO: 
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 ran successfully:
    - 1 Agg_taxi_locations()

This progress looks :) because there were no failed tasks or missing external dependencies

===== Luigi Execution Summary =====

         lon      lat            timestamp
0  103.62704  1.28053  2017-11-12 16:43:06
1  103.62704  1.28053  2017-11-12 16:43:06
2  103.62704  1.28053  2017-11-12 16:43:06
3  103.62704  1.28053  2017-11-12 16:43:06
4  103.62704  1.28053  2017-11-12 16:43:06
Succefully save taxi location data as sqlite db to /output at 2017-11-12
sh: sysctl: command not found
/anaconda/envs/g_dash/lib/python3.4/site-packages/numexpr/cpuinfo.py:76: UserWarning: [Errno 2] No such file or directory: 'sysctl'
  stacklevel=stacklevel + 1):
DEBUG: Checking if Agg_taxi_locations() is complete
/anaconda/envs/g_dash/lib/python3.4/site-packages/luigi/worker.py:295: UserWarning: Task Agg_taxi_locations() without outputs has no custom complete() method
  is_complete = task.complete()
INFO: Informed scheduler that task   Agg_taxi_locations__99914b932b   has status   PENDING
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 1
INFO: [pid 15487] Worker Worker(salt=207063378, workers=1, host=yennanliude-MBP, username=yennanliu, pid=15487) running   Agg_taxi_locations()
INFO: [pid 15487] Worker Worker(salt=207063378, workers=1, host=yennanliude-MBP, username=yennanliu, pid=15487) done      Agg_taxi_locations()
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   Agg_taxi_locations__99914b932b   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
INFO: Worker Worker(salt=207063378, workers=1, host=yennanliude-MBP, username=yennanliu, pid=15487) was stopped. Shutting down Keep-Alive thread
INFO: 
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 ran successfully:
    - 1 Agg_taxi_locations()

This progress looks :) because there were no failed tasks or missing external dependencies

===== Luigi Execution Summary =====

         lon      lat            timestamp
0  103.61429  1.25193  2017-11-12 16:44:05
1  103.61429  1.25193  2017-11-12 16:44:05
2  103.61429  1.25193  2017-11-12 16:44:05
3  103.61429  1.25193  2017-11-12 16:44:05
4  103.61429  1.25193  2017-11-12 16:44:05
Succefully save taxi location data as sqlite db to /output at 2017-11-12
sh: sysctl: command not found
/anaconda/envs/g_dash/lib/python3.4/site-packages/numexpr/cpuinfo.py:76: UserWarning: [Errno 2] No such file or directory: 'sysctl'
  stacklevel=stacklevel + 1):
DEBUG: Checking if Agg_taxi_locations() is complete
/anaconda/envs/g_dash/lib/python3.4/site-packages/luigi/worker.py:295: UserWarning: Task Agg_taxi_locations() without outputs has no custom complete() method
  is_complete = task.complete()
INFO: Informed scheduler that task   Agg_taxi_locations__99914b932b   has status   PENDING
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 1
INFO: [pid 15511] Worker Worker(salt=101028260, workers=1, host=yennanliude-MBP, username=yennanliu, pid=15511) running   Agg_taxi_locations()
INFO: [pid 15511] Worker Worker(salt=101028260, workers=1, host=yennanliude-MBP, username=yennanliu, pid=15511) done      Agg_taxi_locations()
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   Agg_taxi_locations__99914b932b   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
INFO: Worker Worker(salt=101028260, workers=1, host=yennanliude-MBP, username=yennanliu, pid=15511) was stopped. Shutting down Keep-Alive thread
INFO: 
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 ran successfully:
    - 1 Agg_taxi_locations()

This progress looks :) because there were no failed tasks or missing external dependencies

===== Luigi Execution Summary =====

         lon      lat            timestamp
0  103.61422  1.26366  2017-11-12 16:45:05
1  103.61422  1.26366  2017-11-12 16:45:05
2  103.61422  1.26366  2017-11-12 16:45:05
3  103.61422  1.26366  2017-11-12 16:45:05
4  103.61422  1.26366  2017-11-12 16:45:05
Succefully save taxi location data as sqlite db to /output at 2017-11-12
sh: sysctl: command not found
/anaconda/envs/g_dash/lib/python3.4/site-packages/numexpr/cpuinfo.py:76: UserWarning: [Errno 2] No such file or directory: 'sysctl'
  stacklevel=stacklevel + 1):
DEBUG: Checking if Agg_taxi_locations() is complete
/anaconda/envs/g_dash/lib/python3.4/site-packages/luigi/worker.py:295: UserWarning: Task Agg_taxi_locations() without outputs has no custom complete() method
  is_complete = task.complete()
INFO: Informed scheduler that task   Agg_taxi_locations__99914b932b   has status   PENDING
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 1
INFO: [pid 15538] Worker Worker(salt=515978898, workers=1, host=yennanliude-MBP, username=yennanliu, pid=15538) running   Agg_taxi_locations()
INFO: [pid 15538] Worker Worker(salt=515978898, workers=1, host=yennanliude-MBP, username=yennanliu, pid=15538) done      Agg_taxi_locations()
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   Agg_taxi_locations__99914b932b   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
INFO: Worker Worker(salt=515978898, workers=1, host=yennanliude-MBP, username=yennanliu, pid=15538) was stopped. Shutting down Keep-Alive thread
INFO: 
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 ran successfully:
    - 1 Agg_taxi_locations()

This progress looks :) because there were no failed tasks or missing external dependencies

===== Luigi Execution Summary =====

         lon      lat            timestamp
0  103.61676  1.27283  2017-11-12 16:46:06
1  103.61676  1.27283  2017-11-12 16:46:06
2  103.61676  1.27283  2017-11-12 16:46:06
3  103.62706  1.28054  2017-11-12 16:46:06
4  103.62706  1.28054  2017-11-12 16:46:06
Succefully save taxi location data as sqlite db to /output at 2017-11-12
sh: sysctl: command not found
/anaconda/envs/g_dash/lib/python3.4/site-packages/numexpr/cpuinfo.py:76: UserWarning: [Errno 2] No such file or directory: 'sysctl'
  stacklevel=stacklevel + 1):
DEBUG: Checking if Agg_taxi_locations() is complete
/anaconda/envs/g_dash/lib/python3.4/site-packages/luigi/worker.py:295: UserWarning: Task Agg_taxi_locations() without outputs has no custom complete() method
  is_complete = task.complete()
INFO: Informed scheduler that task   Agg_taxi_locations__99914b932b   has status   PENDING
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 1
INFO: [pid 15570] Worker Worker(salt=858894096, workers=1, host=yennanliude-MBP, username=yennanliu, pid=15570) running   Agg_taxi_locations()
INFO: [pid 15570] Worker Worker(salt=858894096, workers=1, host=yennanliude-MBP, username=yennanliu, pid=15570) done      Agg_taxi_locations()
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   Agg_taxi_locations__99914b932b   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
INFO: Worker Worker(salt=858894096, workers=1, host=yennanliude-MBP, username=yennanliu, pid=15570) was stopped. Shutting down Keep-Alive thread
INFO: 
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 ran successfully:
    - 1 Agg_taxi_locations()

This progress looks :) because there were no failed tasks or missing external dependencies

===== Luigi Execution Summary =====

         lon      lat            timestamp
0  103.62119  1.27634  2017-11-12 16:47:06
1  103.62119  1.27634  2017-11-12 16:47:06
2  103.62119  1.27634  2017-11-12 16:47:06
3  103.62119  1.27634  2017-11-12 16:47:06
4  103.62119  1.27634  2017-11-12 16:47:06
Succefully save taxi location data as sqlite db to /output at 2017-11-12
sh: sysctl: command not found
/anaconda/envs/g_dash/lib/python3.4/site-packages/numexpr/cpuinfo.py:76: UserWarning: [Errno 2] No such file or directory: 'sysctl'
  stacklevel=stacklevel + 1):
DEBUG: Checking if Agg_taxi_locations() is complete
/anaconda/envs/g_dash/lib/python3.4/site-packages/luigi/worker.py:295: UserWarning: Task Agg_taxi_locations() without outputs has no custom complete() method
  is_complete = task.complete()
INFO: Informed scheduler that task   Agg_taxi_locations__99914b932b   has status   PENDING
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 1
INFO: [pid 15592] Worker Worker(salt=176426504, workers=1, host=yennanliude-MBP, username=yennanliu, pid=15592) running   Agg_taxi_locations()
INFO: [pid 15592] Worker Worker(salt=176426504, workers=1, host=yennanliude-MBP, username=yennanliu, pid=15592) done      Agg_taxi_locations()
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   Agg_taxi_locations__99914b932b   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
INFO: Worker Worker(salt=176426504, workers=1, host=yennanliude-MBP, username=yennanliu, pid=15592) was stopped. Shutting down Keep-Alive thread
INFO: 
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 ran successfully:
    - 1 Agg_taxi_locations()

This progress looks :) because there were no failed tasks or missing external dependencies

===== Luigi Execution Summary =====

         lon      lat            timestamp
0  103.62331  1.28461  2017-11-12 16:48:05
1  103.62331  1.28461  2017-11-12 16:48:05
2  103.62331  1.28461  2017-11-12 16:48:05
3  103.62331  1.28461  2017-11-12 16:48:05
4  103.62331  1.28461  2017-11-12 16:48:05
Succefully save taxi location data as sqlite db to /output at 2017-11-12
sh: sysctl: command not found
/anaconda/envs/g_dash/lib/python3.4/site-packages/numexpr/cpuinfo.py:76: UserWarning: [Errno 2] No such file or directory: 'sysctl'
  stacklevel=stacklevel + 1):
DEBUG: Checking if Agg_taxi_locations() is complete
/anaconda/envs/g_dash/lib/python3.4/site-packages/luigi/worker.py:295: UserWarning: Task Agg_taxi_locations() without outputs has no custom complete() method
  is_complete = task.complete()
INFO: Informed scheduler that task   Agg_taxi_locations__99914b932b   has status   PENDING
INFO: Done scheduling tasks
INFO: Running Worker with 1 processes
DEBUG: Asking scheduler for work...
DEBUG: Pending tasks: 1
INFO: [pid 15626] Worker Worker(salt=047024476, workers=1, host=yennanliude-MBP, username=yennanliu, pid=15626) running   Agg_taxi_locations()
INFO: [pid 15626] Worker Worker(salt=047024476, workers=1, host=yennanliude-MBP, username=yennanliu, pid=15626) done      Agg_taxi_locations()
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   Agg_taxi_locations__99914b932b   has status   DONE
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
INFO: Worker Worker(salt=047024476, workers=1, host=yennanliude-MBP, username=yennanliu, pid=15626) was stopped. Shutting down Keep-Alive thread
INFO: 
===== Luigi Execution Summary =====

Scheduled 1 tasks of which:
* 1 ran successfully:
    - 1 Agg_taxi_locations()

This progress looks :) because there were no failed tasks or missing external dependencies

===== Luigi Execution Summary =====

         lon      lat            timestamp
0  103.62519  1.28979  2017-11-12 16:49:05
1  103.62519  1.28979  2017-11-12 16:49:05
2  103.62519  1.28979  2017-11-12 16:49:05
3  103.62519  1.28979  2017-11-12 16:49:05
4  103.62519  1.28979  2017-11-12 16:49:05
Succefully save taxi location data as sqlite db to /output at 2017-11-12
